// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mahjong.proto

package com.imooc.netty.mahjong.common.proto;

public interface CreateRoomRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateRoomRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 playerNum = 1;</code>
   */
  int getPlayerNum();

  /**
   * <code>optional int32 baseScore = 2;</code>
   */
  int getBaseScore();
}
