// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mahjong.proto

package com.imooc.netty.mahjong.common.proto;

/**
 * Protobuf type {@code CreateRoomRequest}
 */
public  final class CreateRoomRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CreateRoomRequest)
    CreateRoomRequestOrBuilder {
  // Use CreateRoomRequest.newBuilder() to construct.
  private CreateRoomRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateRoomRequest() {
    playerNum_ = 0;
    baseScore_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CreateRoomRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            playerNum_ = input.readInt32();
            break;
          }
          case 16: {

            baseScore_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.imooc.netty.mahjong.common.proto.Mahjong.internal_static_CreateRoomRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.imooc.netty.mahjong.common.proto.Mahjong.internal_static_CreateRoomRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.imooc.netty.mahjong.common.proto.CreateRoomRequest.class, com.imooc.netty.mahjong.common.proto.CreateRoomRequest.Builder.class);
  }

  public static final int PLAYERNUM_FIELD_NUMBER = 1;
  private int playerNum_;
  /**
   * <code>optional int32 playerNum = 1;</code>
   */
  public int getPlayerNum() {
    return playerNum_;
  }

  public static final int BASESCORE_FIELD_NUMBER = 2;
  private int baseScore_;
  /**
   * <code>optional int32 baseScore = 2;</code>
   */
  public int getBaseScore() {
    return baseScore_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (playerNum_ != 0) {
      output.writeInt32(1, playerNum_);
    }
    if (baseScore_ != 0) {
      output.writeInt32(2, baseScore_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (playerNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, playerNum_);
    }
    if (baseScore_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, baseScore_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.imooc.netty.mahjong.common.proto.CreateRoomRequest)) {
      return super.equals(obj);
    }
    com.imooc.netty.mahjong.common.proto.CreateRoomRequest other = (com.imooc.netty.mahjong.common.proto.CreateRoomRequest) obj;

    boolean result = true;
    result = result && (getPlayerNum()
        == other.getPlayerNum());
    result = result && (getBaseScore()
        == other.getBaseScore());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + PLAYERNUM_FIELD_NUMBER;
    hash = (53 * hash) + getPlayerNum();
    hash = (37 * hash) + BASESCORE_FIELD_NUMBER;
    hash = (53 * hash) + getBaseScore();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.imooc.netty.mahjong.common.proto.CreateRoomRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.imooc.netty.mahjong.common.proto.CreateRoomRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.imooc.netty.mahjong.common.proto.CreateRoomRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.imooc.netty.mahjong.common.proto.CreateRoomRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.imooc.netty.mahjong.common.proto.CreateRoomRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.imooc.netty.mahjong.common.proto.CreateRoomRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.imooc.netty.mahjong.common.proto.CreateRoomRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.imooc.netty.mahjong.common.proto.CreateRoomRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.imooc.netty.mahjong.common.proto.CreateRoomRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.imooc.netty.mahjong.common.proto.CreateRoomRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.imooc.netty.mahjong.common.proto.CreateRoomRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CreateRoomRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CreateRoomRequest)
      com.imooc.netty.mahjong.common.proto.CreateRoomRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.imooc.netty.mahjong.common.proto.Mahjong.internal_static_CreateRoomRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.imooc.netty.mahjong.common.proto.Mahjong.internal_static_CreateRoomRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.imooc.netty.mahjong.common.proto.CreateRoomRequest.class, com.imooc.netty.mahjong.common.proto.CreateRoomRequest.Builder.class);
    }

    // Construct using com.imooc.netty.mahjong.common.proto.CreateRoomRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      playerNum_ = 0;

      baseScore_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.imooc.netty.mahjong.common.proto.Mahjong.internal_static_CreateRoomRequest_descriptor;
    }

    public com.imooc.netty.mahjong.common.proto.CreateRoomRequest getDefaultInstanceForType() {
      return com.imooc.netty.mahjong.common.proto.CreateRoomRequest.getDefaultInstance();
    }

    public com.imooc.netty.mahjong.common.proto.CreateRoomRequest build() {
      com.imooc.netty.mahjong.common.proto.CreateRoomRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.imooc.netty.mahjong.common.proto.CreateRoomRequest buildPartial() {
      com.imooc.netty.mahjong.common.proto.CreateRoomRequest result = new com.imooc.netty.mahjong.common.proto.CreateRoomRequest(this);
      result.playerNum_ = playerNum_;
      result.baseScore_ = baseScore_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.imooc.netty.mahjong.common.proto.CreateRoomRequest) {
        return mergeFrom((com.imooc.netty.mahjong.common.proto.CreateRoomRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.imooc.netty.mahjong.common.proto.CreateRoomRequest other) {
      if (other == com.imooc.netty.mahjong.common.proto.CreateRoomRequest.getDefaultInstance()) return this;
      if (other.getPlayerNum() != 0) {
        setPlayerNum(other.getPlayerNum());
      }
      if (other.getBaseScore() != 0) {
        setBaseScore(other.getBaseScore());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.imooc.netty.mahjong.common.proto.CreateRoomRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.imooc.netty.mahjong.common.proto.CreateRoomRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int playerNum_ ;
    /**
     * <code>optional int32 playerNum = 1;</code>
     */
    public int getPlayerNum() {
      return playerNum_;
    }
    /**
     * <code>optional int32 playerNum = 1;</code>
     */
    public Builder setPlayerNum(int value) {
      
      playerNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 playerNum = 1;</code>
     */
    public Builder clearPlayerNum() {
      
      playerNum_ = 0;
      onChanged();
      return this;
    }

    private int baseScore_ ;
    /**
     * <code>optional int32 baseScore = 2;</code>
     */
    public int getBaseScore() {
      return baseScore_;
    }
    /**
     * <code>optional int32 baseScore = 2;</code>
     */
    public Builder setBaseScore(int value) {
      
      baseScore_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 baseScore = 2;</code>
     */
    public Builder clearBaseScore() {
      
      baseScore_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:CreateRoomRequest)
  }

  // @@protoc_insertion_point(class_scope:CreateRoomRequest)
  private static final com.imooc.netty.mahjong.common.proto.CreateRoomRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.imooc.netty.mahjong.common.proto.CreateRoomRequest();
  }

  public static com.imooc.netty.mahjong.common.proto.CreateRoomRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateRoomRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateRoomRequest>() {
    public CreateRoomRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateRoomRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateRoomRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateRoomRequest> getParserForType() {
    return PARSER;
  }

  public com.imooc.netty.mahjong.common.proto.CreateRoomRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

