// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mahjong.proto

package com.imooc.netty.mahjong.common.proto;

public interface EnterRoomResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnterRoomResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool result = 1;</code>
   */
  boolean getResult();

  /**
   * <code>optional string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
