// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mahjong.proto

package com.imooc.netty.mahjong.common.proto;

public interface EnterRoomRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnterRoomRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 roomId = 1;</code>
   */
  long getRoomId();
}
