// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mahjong.proto

package com.imooc.netty.mahjong.common.proto;

/**
 * Protobuf type {@code GameOverNotification}
 */
public  final class GameOverNotification extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GameOverNotification)
    GameOverNotificationOrBuilder {
  // Use GameOverNotification.newBuilder() to construct.
  private GameOverNotification(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GameOverNotification() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GameOverNotification(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.imooc.netty.mahjong.common.proto.RoomMsg.Builder subBuilder = null;
            if (room_ != null) {
              subBuilder = room_.toBuilder();
            }
            room_ = input.readMessage(com.imooc.netty.mahjong.common.proto.RoomMsg.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(room_);
              room_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.imooc.netty.mahjong.common.proto.Mahjong.internal_static_GameOverNotification_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.imooc.netty.mahjong.common.proto.Mahjong.internal_static_GameOverNotification_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.imooc.netty.mahjong.common.proto.GameOverNotification.class, com.imooc.netty.mahjong.common.proto.GameOverNotification.Builder.class);
  }

  public static final int ROOM_FIELD_NUMBER = 1;
  private com.imooc.netty.mahjong.common.proto.RoomMsg room_;
  /**
   * <code>optional .RoomMsg room = 1;</code>
   */
  public boolean hasRoom() {
    return room_ != null;
  }
  /**
   * <code>optional .RoomMsg room = 1;</code>
   */
  public com.imooc.netty.mahjong.common.proto.RoomMsg getRoom() {
    return room_ == null ? com.imooc.netty.mahjong.common.proto.RoomMsg.getDefaultInstance() : room_;
  }
  /**
   * <code>optional .RoomMsg room = 1;</code>
   */
  public com.imooc.netty.mahjong.common.proto.RoomMsgOrBuilder getRoomOrBuilder() {
    return getRoom();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (room_ != null) {
      output.writeMessage(1, getRoom());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (room_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRoom());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.imooc.netty.mahjong.common.proto.GameOverNotification)) {
      return super.equals(obj);
    }
    com.imooc.netty.mahjong.common.proto.GameOverNotification other = (com.imooc.netty.mahjong.common.proto.GameOverNotification) obj;

    boolean result = true;
    result = result && (hasRoom() == other.hasRoom());
    if (hasRoom()) {
      result = result && getRoom()
          .equals(other.getRoom());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasRoom()) {
      hash = (37 * hash) + ROOM_FIELD_NUMBER;
      hash = (53 * hash) + getRoom().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.imooc.netty.mahjong.common.proto.GameOverNotification parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.imooc.netty.mahjong.common.proto.GameOverNotification parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.imooc.netty.mahjong.common.proto.GameOverNotification parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.imooc.netty.mahjong.common.proto.GameOverNotification parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.imooc.netty.mahjong.common.proto.GameOverNotification parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.imooc.netty.mahjong.common.proto.GameOverNotification parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.imooc.netty.mahjong.common.proto.GameOverNotification parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.imooc.netty.mahjong.common.proto.GameOverNotification parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.imooc.netty.mahjong.common.proto.GameOverNotification parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.imooc.netty.mahjong.common.proto.GameOverNotification parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.imooc.netty.mahjong.common.proto.GameOverNotification prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GameOverNotification}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GameOverNotification)
      com.imooc.netty.mahjong.common.proto.GameOverNotificationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.imooc.netty.mahjong.common.proto.Mahjong.internal_static_GameOverNotification_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.imooc.netty.mahjong.common.proto.Mahjong.internal_static_GameOverNotification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.imooc.netty.mahjong.common.proto.GameOverNotification.class, com.imooc.netty.mahjong.common.proto.GameOverNotification.Builder.class);
    }

    // Construct using com.imooc.netty.mahjong.common.proto.GameOverNotification.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (roomBuilder_ == null) {
        room_ = null;
      } else {
        room_ = null;
        roomBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.imooc.netty.mahjong.common.proto.Mahjong.internal_static_GameOverNotification_descriptor;
    }

    public com.imooc.netty.mahjong.common.proto.GameOverNotification getDefaultInstanceForType() {
      return com.imooc.netty.mahjong.common.proto.GameOverNotification.getDefaultInstance();
    }

    public com.imooc.netty.mahjong.common.proto.GameOverNotification build() {
      com.imooc.netty.mahjong.common.proto.GameOverNotification result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.imooc.netty.mahjong.common.proto.GameOverNotification buildPartial() {
      com.imooc.netty.mahjong.common.proto.GameOverNotification result = new com.imooc.netty.mahjong.common.proto.GameOverNotification(this);
      if (roomBuilder_ == null) {
        result.room_ = room_;
      } else {
        result.room_ = roomBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.imooc.netty.mahjong.common.proto.GameOverNotification) {
        return mergeFrom((com.imooc.netty.mahjong.common.proto.GameOverNotification)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.imooc.netty.mahjong.common.proto.GameOverNotification other) {
      if (other == com.imooc.netty.mahjong.common.proto.GameOverNotification.getDefaultInstance()) return this;
      if (other.hasRoom()) {
        mergeRoom(other.getRoom());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.imooc.netty.mahjong.common.proto.GameOverNotification parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.imooc.netty.mahjong.common.proto.GameOverNotification) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.imooc.netty.mahjong.common.proto.RoomMsg room_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.imooc.netty.mahjong.common.proto.RoomMsg, com.imooc.netty.mahjong.common.proto.RoomMsg.Builder, com.imooc.netty.mahjong.common.proto.RoomMsgOrBuilder> roomBuilder_;
    /**
     * <code>optional .RoomMsg room = 1;</code>
     */
    public boolean hasRoom() {
      return roomBuilder_ != null || room_ != null;
    }
    /**
     * <code>optional .RoomMsg room = 1;</code>
     */
    public com.imooc.netty.mahjong.common.proto.RoomMsg getRoom() {
      if (roomBuilder_ == null) {
        return room_ == null ? com.imooc.netty.mahjong.common.proto.RoomMsg.getDefaultInstance() : room_;
      } else {
        return roomBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .RoomMsg room = 1;</code>
     */
    public Builder setRoom(com.imooc.netty.mahjong.common.proto.RoomMsg value) {
      if (roomBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        room_ = value;
        onChanged();
      } else {
        roomBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .RoomMsg room = 1;</code>
     */
    public Builder setRoom(
        com.imooc.netty.mahjong.common.proto.RoomMsg.Builder builderForValue) {
      if (roomBuilder_ == null) {
        room_ = builderForValue.build();
        onChanged();
      } else {
        roomBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .RoomMsg room = 1;</code>
     */
    public Builder mergeRoom(com.imooc.netty.mahjong.common.proto.RoomMsg value) {
      if (roomBuilder_ == null) {
        if (room_ != null) {
          room_ =
            com.imooc.netty.mahjong.common.proto.RoomMsg.newBuilder(room_).mergeFrom(value).buildPartial();
        } else {
          room_ = value;
        }
        onChanged();
      } else {
        roomBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .RoomMsg room = 1;</code>
     */
    public Builder clearRoom() {
      if (roomBuilder_ == null) {
        room_ = null;
        onChanged();
      } else {
        room_ = null;
        roomBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .RoomMsg room = 1;</code>
     */
    public com.imooc.netty.mahjong.common.proto.RoomMsg.Builder getRoomBuilder() {
      
      onChanged();
      return getRoomFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .RoomMsg room = 1;</code>
     */
    public com.imooc.netty.mahjong.common.proto.RoomMsgOrBuilder getRoomOrBuilder() {
      if (roomBuilder_ != null) {
        return roomBuilder_.getMessageOrBuilder();
      } else {
        return room_ == null ?
            com.imooc.netty.mahjong.common.proto.RoomMsg.getDefaultInstance() : room_;
      }
    }
    /**
     * <code>optional .RoomMsg room = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.imooc.netty.mahjong.common.proto.RoomMsg, com.imooc.netty.mahjong.common.proto.RoomMsg.Builder, com.imooc.netty.mahjong.common.proto.RoomMsgOrBuilder> 
        getRoomFieldBuilder() {
      if (roomBuilder_ == null) {
        roomBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.imooc.netty.mahjong.common.proto.RoomMsg, com.imooc.netty.mahjong.common.proto.RoomMsg.Builder, com.imooc.netty.mahjong.common.proto.RoomMsgOrBuilder>(
                getRoom(),
                getParentForChildren(),
                isClean());
        room_ = null;
      }
      return roomBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:GameOverNotification)
  }

  // @@protoc_insertion_point(class_scope:GameOverNotification)
  private static final com.imooc.netty.mahjong.common.proto.GameOverNotification DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.imooc.netty.mahjong.common.proto.GameOverNotification();
  }

  public static com.imooc.netty.mahjong.common.proto.GameOverNotification getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GameOverNotification>
      PARSER = new com.google.protobuf.AbstractParser<GameOverNotification>() {
    public GameOverNotification parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameOverNotification(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GameOverNotification> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GameOverNotification> getParserForType() {
    return PARSER;
  }

  public com.imooc.netty.mahjong.common.proto.GameOverNotification getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

