// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mahjong.proto

package com.imooc.netty.mahjong.common.proto;

public interface GameOverNotificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GameOverNotification)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .RoomMsg room = 1;</code>
   */
  boolean hasRoom();
  /**
   * <code>optional .RoomMsg room = 1;</code>
   */
  com.imooc.netty.mahjong.common.proto.RoomMsg getRoom();
  /**
   * <code>optional .RoomMsg room = 1;</code>
   */
  com.imooc.netty.mahjong.common.proto.RoomMsgOrBuilder getRoomOrBuilder();
}
