// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mahjong.proto

package com.imooc.netty.mahjong.common.proto;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool result = 1;</code>
   */
  boolean getResult();

  /**
   * <code>optional .PlayerMsg player = 2;</code>
   */
  boolean hasPlayer();
  /**
   * <code>optional .PlayerMsg player = 2;</code>
   */
  com.imooc.netty.mahjong.common.proto.PlayerMsg getPlayer();
  /**
   * <code>optional .PlayerMsg player = 2;</code>
   */
  com.imooc.netty.mahjong.common.proto.PlayerMsgOrBuilder getPlayerOrBuilder();

  /**
   * <code>optional string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
