// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mahjong.proto

package com.imooc.netty.mahjong.common.proto;

public interface OperationResultNotificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OperationResultNotification)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 operation = 1;</code>
   */
  int getOperation();

  /**
   * <code>optional int32 pos = 2;</code>
   */
  int getPos();

  /**
   * <code>optional int32 card = 3;</code>
   */
  int getCard();
}
