// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mahjong.proto

package com.imooc.netty.mahjong.common.proto;

public interface PlayerMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PlayerMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   **
   * 唯一标识id
   * </pre>
   *
   * <code>optional int64 id = 1;</code>
   */
  long getId();

  /**
   * <pre>
   **
   * 用户名
   * </pre>
   *
   * <code>optional string username = 2;</code>
   */
  java.lang.String getUsername();
  /**
   * <pre>
   **
   * 用户名
   * </pre>
   *
   * <code>optional string username = 2;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <pre>
   **
   * 密码
   * </pre>
   *
   * <code>optional string password = 3;</code>
   */
  java.lang.String getPassword();
  /**
   * <pre>
   **
   * 密码
   * </pre>
   *
   * <code>optional string password = 3;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <pre>
   **
   * 玩家的积分
   * </pre>
   *
   * <code>optional int32 score = 4;</code>
   */
  int getScore();

  /**
   * <pre>
   **
   * 玩家在房间的位置
   * </pre>
   *
   * <code>optional int32 pos = 5;</code>
   */
  int getPos();

  /**
   * <pre>
   **
   * 手牌列表
   * </pre>
   *
   * <code>optional bytes cards = 6;</code>
   */
  com.google.protobuf.ByteString getCards();

  /**
   * <pre>
   **
   * 打出的牌
   * </pre>
   *
   * <code>optional bytes chuCards = 7;</code>
   */
  com.google.protobuf.ByteString getChuCards();

  /**
   * <pre>
   **
   * 碰的牌
   * </pre>
   *
   * <code>optional bytes pengList = 8;</code>
   */
  com.google.protobuf.ByteString getPengList();

  /**
   * <pre>
   **
   * 杠的牌
   * </pre>
   *
   * <code>optional bytes gangList = 9;</code>
   */
  com.google.protobuf.ByteString getGangList();
}
