// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mahjong.proto

package com.imooc.netty.mahjong.common.proto;

/**
 * Protobuf type {@code PlayerMsg}
 */
public  final class PlayerMsg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PlayerMsg)
    PlayerMsgOrBuilder {
  // Use PlayerMsg.newBuilder() to construct.
  private PlayerMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PlayerMsg() {
    id_ = 0L;
    username_ = "";
    password_ = "";
    score_ = 0;
    pos_ = 0;
    cards_ = com.google.protobuf.ByteString.EMPTY;
    chuCards_ = com.google.protobuf.ByteString.EMPTY;
    pengList_ = com.google.protobuf.ByteString.EMPTY;
    gangList_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private PlayerMsg(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            username_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            password_ = s;
            break;
          }
          case 32: {

            score_ = input.readInt32();
            break;
          }
          case 40: {

            pos_ = input.readInt32();
            break;
          }
          case 50: {

            cards_ = input.readBytes();
            break;
          }
          case 58: {

            chuCards_ = input.readBytes();
            break;
          }
          case 66: {

            pengList_ = input.readBytes();
            break;
          }
          case 74: {

            gangList_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.imooc.netty.mahjong.common.proto.Mahjong.internal_static_PlayerMsg_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.imooc.netty.mahjong.common.proto.Mahjong.internal_static_PlayerMsg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.imooc.netty.mahjong.common.proto.PlayerMsg.class, com.imooc.netty.mahjong.common.proto.PlayerMsg.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <pre>
   **
   * 唯一标识id
   * </pre>
   *
   * <code>optional int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int USERNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object username_;
  /**
   * <pre>
   **
   * 用户名
   * </pre>
   *
   * <code>optional string username = 2;</code>
   */
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 用户名
   * </pre>
   *
   * <code>optional string username = 2;</code>
   */
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 3;
  private volatile java.lang.Object password_;
  /**
   * <pre>
   **
   * 密码
   * </pre>
   *
   * <code>optional string password = 3;</code>
   */
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 密码
   * </pre>
   *
   * <code>optional string password = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCORE_FIELD_NUMBER = 4;
  private int score_;
  /**
   * <pre>
   **
   * 玩家的积分
   * </pre>
   *
   * <code>optional int32 score = 4;</code>
   */
  public int getScore() {
    return score_;
  }

  public static final int POS_FIELD_NUMBER = 5;
  private int pos_;
  /**
   * <pre>
   **
   * 玩家在房间的位置
   * </pre>
   *
   * <code>optional int32 pos = 5;</code>
   */
  public int getPos() {
    return pos_;
  }

  public static final int CARDS_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString cards_;
  /**
   * <pre>
   **
   * 手牌列表
   * </pre>
   *
   * <code>optional bytes cards = 6;</code>
   */
  public com.google.protobuf.ByteString getCards() {
    return cards_;
  }

  public static final int CHUCARDS_FIELD_NUMBER = 7;
  private com.google.protobuf.ByteString chuCards_;
  /**
   * <pre>
   **
   * 打出的牌
   * </pre>
   *
   * <code>optional bytes chuCards = 7;</code>
   */
  public com.google.protobuf.ByteString getChuCards() {
    return chuCards_;
  }

  public static final int PENGLIST_FIELD_NUMBER = 8;
  private com.google.protobuf.ByteString pengList_;
  /**
   * <pre>
   **
   * 碰的牌
   * </pre>
   *
   * <code>optional bytes pengList = 8;</code>
   */
  public com.google.protobuf.ByteString getPengList() {
    return pengList_;
  }

  public static final int GANGLIST_FIELD_NUMBER = 9;
  private com.google.protobuf.ByteString gangList_;
  /**
   * <pre>
   **
   * 杠的牌
   * </pre>
   *
   * <code>optional bytes gangList = 9;</code>
   */
  public com.google.protobuf.ByteString getGangList() {
    return gangList_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getUsernameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, username_);
    }
    if (!getPasswordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
    }
    if (score_ != 0) {
      output.writeInt32(4, score_);
    }
    if (pos_ != 0) {
      output.writeInt32(5, pos_);
    }
    if (!cards_.isEmpty()) {
      output.writeBytes(6, cards_);
    }
    if (!chuCards_.isEmpty()) {
      output.writeBytes(7, chuCards_);
    }
    if (!pengList_.isEmpty()) {
      output.writeBytes(8, pengList_);
    }
    if (!gangList_.isEmpty()) {
      output.writeBytes(9, gangList_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getUsernameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, username_);
    }
    if (!getPasswordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
    }
    if (score_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, score_);
    }
    if (pos_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, pos_);
    }
    if (!cards_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, cards_);
    }
    if (!chuCards_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, chuCards_);
    }
    if (!pengList_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(8, pengList_);
    }
    if (!gangList_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(9, gangList_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.imooc.netty.mahjong.common.proto.PlayerMsg)) {
      return super.equals(obj);
    }
    com.imooc.netty.mahjong.common.proto.PlayerMsg other = (com.imooc.netty.mahjong.common.proto.PlayerMsg) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getUsername()
        .equals(other.getUsername());
    result = result && getPassword()
        .equals(other.getPassword());
    result = result && (getScore()
        == other.getScore());
    result = result && (getPos()
        == other.getPos());
    result = result && getCards()
        .equals(other.getCards());
    result = result && getChuCards()
        .equals(other.getChuCards());
    result = result && getPengList()
        .equals(other.getPengList());
    result = result && getGangList()
        .equals(other.getGangList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    hash = (37 * hash) + SCORE_FIELD_NUMBER;
    hash = (53 * hash) + getScore();
    hash = (37 * hash) + POS_FIELD_NUMBER;
    hash = (53 * hash) + getPos();
    hash = (37 * hash) + CARDS_FIELD_NUMBER;
    hash = (53 * hash) + getCards().hashCode();
    hash = (37 * hash) + CHUCARDS_FIELD_NUMBER;
    hash = (53 * hash) + getChuCards().hashCode();
    hash = (37 * hash) + PENGLIST_FIELD_NUMBER;
    hash = (53 * hash) + getPengList().hashCode();
    hash = (37 * hash) + GANGLIST_FIELD_NUMBER;
    hash = (53 * hash) + getGangList().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.imooc.netty.mahjong.common.proto.PlayerMsg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.imooc.netty.mahjong.common.proto.PlayerMsg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.imooc.netty.mahjong.common.proto.PlayerMsg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.imooc.netty.mahjong.common.proto.PlayerMsg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.imooc.netty.mahjong.common.proto.PlayerMsg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.imooc.netty.mahjong.common.proto.PlayerMsg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.imooc.netty.mahjong.common.proto.PlayerMsg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.imooc.netty.mahjong.common.proto.PlayerMsg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.imooc.netty.mahjong.common.proto.PlayerMsg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.imooc.netty.mahjong.common.proto.PlayerMsg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.imooc.netty.mahjong.common.proto.PlayerMsg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PlayerMsg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PlayerMsg)
      com.imooc.netty.mahjong.common.proto.PlayerMsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.imooc.netty.mahjong.common.proto.Mahjong.internal_static_PlayerMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.imooc.netty.mahjong.common.proto.Mahjong.internal_static_PlayerMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.imooc.netty.mahjong.common.proto.PlayerMsg.class, com.imooc.netty.mahjong.common.proto.PlayerMsg.Builder.class);
    }

    // Construct using com.imooc.netty.mahjong.common.proto.PlayerMsg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0L;

      username_ = "";

      password_ = "";

      score_ = 0;

      pos_ = 0;

      cards_ = com.google.protobuf.ByteString.EMPTY;

      chuCards_ = com.google.protobuf.ByteString.EMPTY;

      pengList_ = com.google.protobuf.ByteString.EMPTY;

      gangList_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.imooc.netty.mahjong.common.proto.Mahjong.internal_static_PlayerMsg_descriptor;
    }

    public com.imooc.netty.mahjong.common.proto.PlayerMsg getDefaultInstanceForType() {
      return com.imooc.netty.mahjong.common.proto.PlayerMsg.getDefaultInstance();
    }

    public com.imooc.netty.mahjong.common.proto.PlayerMsg build() {
      com.imooc.netty.mahjong.common.proto.PlayerMsg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.imooc.netty.mahjong.common.proto.PlayerMsg buildPartial() {
      com.imooc.netty.mahjong.common.proto.PlayerMsg result = new com.imooc.netty.mahjong.common.proto.PlayerMsg(this);
      result.id_ = id_;
      result.username_ = username_;
      result.password_ = password_;
      result.score_ = score_;
      result.pos_ = pos_;
      result.cards_ = cards_;
      result.chuCards_ = chuCards_;
      result.pengList_ = pengList_;
      result.gangList_ = gangList_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.imooc.netty.mahjong.common.proto.PlayerMsg) {
        return mergeFrom((com.imooc.netty.mahjong.common.proto.PlayerMsg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.imooc.netty.mahjong.common.proto.PlayerMsg other) {
      if (other == com.imooc.netty.mahjong.common.proto.PlayerMsg.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        onChanged();
      }
      if (other.getScore() != 0) {
        setScore(other.getScore());
      }
      if (other.getPos() != 0) {
        setPos(other.getPos());
      }
      if (other.getCards() != com.google.protobuf.ByteString.EMPTY) {
        setCards(other.getCards());
      }
      if (other.getChuCards() != com.google.protobuf.ByteString.EMPTY) {
        setChuCards(other.getChuCards());
      }
      if (other.getPengList() != com.google.protobuf.ByteString.EMPTY) {
        setPengList(other.getPengList());
      }
      if (other.getGangList() != com.google.protobuf.ByteString.EMPTY) {
        setGangList(other.getGangList());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.imooc.netty.mahjong.common.proto.PlayerMsg parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.imooc.netty.mahjong.common.proto.PlayerMsg) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <pre>
     **
     * 唯一标识id
     * </pre>
     *
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <pre>
     **
     * 唯一标识id
     * </pre>
     *
     * <code>optional int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 唯一标识id
     * </pre>
     *
     * <code>optional int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object username_ = "";
    /**
     * <pre>
     **
     * 用户名
     * </pre>
     *
     * <code>optional string username = 2;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 用户名
     * </pre>
     *
     * <code>optional string username = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 用户名
     * </pre>
     *
     * <code>optional string username = 2;</code>
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      username_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 用户名
     * </pre>
     *
     * <code>optional string username = 2;</code>
     */
    public Builder clearUsername() {
      
      username_ = getDefaultInstance().getUsername();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 用户名
     * </pre>
     *
     * <code>optional string username = 2;</code>
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      username_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object password_ = "";
    /**
     * <pre>
     **
     * 密码
     * </pre>
     *
     * <code>optional string password = 3;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 密码
     * </pre>
     *
     * <code>optional string password = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 密码
     * </pre>
     *
     * <code>optional string password = 3;</code>
     */
    public Builder setPassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 密码
     * </pre>
     *
     * <code>optional string password = 3;</code>
     */
    public Builder clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 密码
     * </pre>
     *
     * <code>optional string password = 3;</code>
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      password_ = value;
      onChanged();
      return this;
    }

    private int score_ ;
    /**
     * <pre>
     **
     * 玩家的积分
     * </pre>
     *
     * <code>optional int32 score = 4;</code>
     */
    public int getScore() {
      return score_;
    }
    /**
     * <pre>
     **
     * 玩家的积分
     * </pre>
     *
     * <code>optional int32 score = 4;</code>
     */
    public Builder setScore(int value) {
      
      score_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 玩家的积分
     * </pre>
     *
     * <code>optional int32 score = 4;</code>
     */
    public Builder clearScore() {
      
      score_ = 0;
      onChanged();
      return this;
    }

    private int pos_ ;
    /**
     * <pre>
     **
     * 玩家在房间的位置
     * </pre>
     *
     * <code>optional int32 pos = 5;</code>
     */
    public int getPos() {
      return pos_;
    }
    /**
     * <pre>
     **
     * 玩家在房间的位置
     * </pre>
     *
     * <code>optional int32 pos = 5;</code>
     */
    public Builder setPos(int value) {
      
      pos_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 玩家在房间的位置
     * </pre>
     *
     * <code>optional int32 pos = 5;</code>
     */
    public Builder clearPos() {
      
      pos_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString cards_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     **
     * 手牌列表
     * </pre>
     *
     * <code>optional bytes cards = 6;</code>
     */
    public com.google.protobuf.ByteString getCards() {
      return cards_;
    }
    /**
     * <pre>
     **
     * 手牌列表
     * </pre>
     *
     * <code>optional bytes cards = 6;</code>
     */
    public Builder setCards(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cards_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 手牌列表
     * </pre>
     *
     * <code>optional bytes cards = 6;</code>
     */
    public Builder clearCards() {
      
      cards_ = getDefaultInstance().getCards();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString chuCards_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     **
     * 打出的牌
     * </pre>
     *
     * <code>optional bytes chuCards = 7;</code>
     */
    public com.google.protobuf.ByteString getChuCards() {
      return chuCards_;
    }
    /**
     * <pre>
     **
     * 打出的牌
     * </pre>
     *
     * <code>optional bytes chuCards = 7;</code>
     */
    public Builder setChuCards(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      chuCards_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 打出的牌
     * </pre>
     *
     * <code>optional bytes chuCards = 7;</code>
     */
    public Builder clearChuCards() {
      
      chuCards_ = getDefaultInstance().getChuCards();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString pengList_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     **
     * 碰的牌
     * </pre>
     *
     * <code>optional bytes pengList = 8;</code>
     */
    public com.google.protobuf.ByteString getPengList() {
      return pengList_;
    }
    /**
     * <pre>
     **
     * 碰的牌
     * </pre>
     *
     * <code>optional bytes pengList = 8;</code>
     */
    public Builder setPengList(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pengList_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 碰的牌
     * </pre>
     *
     * <code>optional bytes pengList = 8;</code>
     */
    public Builder clearPengList() {
      
      pengList_ = getDefaultInstance().getPengList();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString gangList_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     **
     * 杠的牌
     * </pre>
     *
     * <code>optional bytes gangList = 9;</code>
     */
    public com.google.protobuf.ByteString getGangList() {
      return gangList_;
    }
    /**
     * <pre>
     **
     * 杠的牌
     * </pre>
     *
     * <code>optional bytes gangList = 9;</code>
     */
    public Builder setGangList(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gangList_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 杠的牌
     * </pre>
     *
     * <code>optional bytes gangList = 9;</code>
     */
    public Builder clearGangList() {
      
      gangList_ = getDefaultInstance().getGangList();
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:PlayerMsg)
  }

  // @@protoc_insertion_point(class_scope:PlayerMsg)
  private static final com.imooc.netty.mahjong.common.proto.PlayerMsg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.imooc.netty.mahjong.common.proto.PlayerMsg();
  }

  public static com.imooc.netty.mahjong.common.proto.PlayerMsg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PlayerMsg>
      PARSER = new com.google.protobuf.AbstractParser<PlayerMsg>() {
    public PlayerMsg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerMsg(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PlayerMsg> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PlayerMsg> getParserForType() {
    return PARSER;
  }

  public com.imooc.netty.mahjong.common.proto.PlayerMsg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

