// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mahjong.proto

package com.imooc.netty.mahjong.common.proto;

/**
 * Protobuf enum {@code RoomStatus}
 */
public enum RoomStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   **
   * 等待其他玩家进入房间
   * </pre>
   *
   * <code>STATUS_WAITING_PLAYER = 0;</code>
   */
  STATUS_WAITING_PLAYER(0),
  /**
   * <pre>
   **
   * 游戏开始
   * </pre>
   *
   * <code>STATUS_GAME_STARTING = 1;</code>
   */
  STATUS_GAME_STARTING(1),
  /**
   * <pre>
   **
   * 等待玩家出牌
   * </pre>
   *
   * <code>STATUS_WAITING_CHU = 2;</code>
   */
  STATUS_WAITING_CHU(2),
  /**
   * <pre>
   **
   * 等待其他玩家操作（碰、杠、胡）
   * </pre>
   *
   * <code>STATUS_WAITING_OPERATION = 3;</code>
   */
  STATUS_WAITING_OPERATION(3),
  /**
   * <pre>
   **
   * 游戏结束
   * </pre>
   *
   * <code>STATUS_GAME_OVER = 4;</code>
   */
  STATUS_GAME_OVER(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   **
   * 等待其他玩家进入房间
   * </pre>
   *
   * <code>STATUS_WAITING_PLAYER = 0;</code>
   */
  public static final int STATUS_WAITING_PLAYER_VALUE = 0;
  /**
   * <pre>
   **
   * 游戏开始
   * </pre>
   *
   * <code>STATUS_GAME_STARTING = 1;</code>
   */
  public static final int STATUS_GAME_STARTING_VALUE = 1;
  /**
   * <pre>
   **
   * 等待玩家出牌
   * </pre>
   *
   * <code>STATUS_WAITING_CHU = 2;</code>
   */
  public static final int STATUS_WAITING_CHU_VALUE = 2;
  /**
   * <pre>
   **
   * 等待其他玩家操作（碰、杠、胡）
   * </pre>
   *
   * <code>STATUS_WAITING_OPERATION = 3;</code>
   */
  public static final int STATUS_WAITING_OPERATION_VALUE = 3;
  /**
   * <pre>
   **
   * 游戏结束
   * </pre>
   *
   * <code>STATUS_GAME_OVER = 4;</code>
   */
  public static final int STATUS_GAME_OVER_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RoomStatus valueOf(int value) {
    return forNumber(value);
  }

  public static RoomStatus forNumber(int value) {
    switch (value) {
      case 0: return STATUS_WAITING_PLAYER;
      case 1: return STATUS_GAME_STARTING;
      case 2: return STATUS_WAITING_CHU;
      case 3: return STATUS_WAITING_OPERATION;
      case 4: return STATUS_GAME_OVER;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RoomStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RoomStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RoomStatus>() {
          public RoomStatus findValueByNumber(int number) {
            return RoomStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.imooc.netty.mahjong.common.proto.Mahjong.getDescriptor()
        .getEnumTypes().get(0);
  }

  private static final RoomStatus[] VALUES = values();

  public static RoomStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RoomStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:RoomStatus)
}

