// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mahjong.proto

package com.imooc.netty.mahjong.common.proto;

public interface SettlementNotificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SettlementNotification)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 scores = 1;</code>
   */
  java.util.List<java.lang.Integer> getScoresList();
  /**
   * <code>repeated int32 scores = 1;</code>
   */
  int getScoresCount();
  /**
   * <code>repeated int32 scores = 1;</code>
   */
  int getScores(int index);
}
