// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mahjong.proto

package com.imooc.netty.mahjong.common.proto;

/**
 * Protobuf type {@code SettlementNotification}
 */
public  final class SettlementNotification extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SettlementNotification)
    SettlementNotificationOrBuilder {
  // Use SettlementNotification.newBuilder() to construct.
  private SettlementNotification(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SettlementNotification() {
    scores_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SettlementNotification(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              scores_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            scores_.add(input.readInt32());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
              scores_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              scores_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        scores_ = java.util.Collections.unmodifiableList(scores_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.imooc.netty.mahjong.common.proto.Mahjong.internal_static_SettlementNotification_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.imooc.netty.mahjong.common.proto.Mahjong.internal_static_SettlementNotification_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.imooc.netty.mahjong.common.proto.SettlementNotification.class, com.imooc.netty.mahjong.common.proto.SettlementNotification.Builder.class);
  }

  public static final int SCORES_FIELD_NUMBER = 1;
  private java.util.List<java.lang.Integer> scores_;
  /**
   * <code>repeated int32 scores = 1;</code>
   */
  public java.util.List<java.lang.Integer>
      getScoresList() {
    return scores_;
  }
  /**
   * <code>repeated int32 scores = 1;</code>
   */
  public int getScoresCount() {
    return scores_.size();
  }
  /**
   * <code>repeated int32 scores = 1;</code>
   */
  public int getScores(int index) {
    return scores_.get(index);
  }
  private int scoresMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getScoresList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(scoresMemoizedSerializedSize);
    }
    for (int i = 0; i < scores_.size(); i++) {
      output.writeInt32NoTag(scores_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < scores_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(scores_.get(i));
      }
      size += dataSize;
      if (!getScoresList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      scoresMemoizedSerializedSize = dataSize;
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.imooc.netty.mahjong.common.proto.SettlementNotification)) {
      return super.equals(obj);
    }
    com.imooc.netty.mahjong.common.proto.SettlementNotification other = (com.imooc.netty.mahjong.common.proto.SettlementNotification) obj;

    boolean result = true;
    result = result && getScoresList()
        .equals(other.getScoresList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getScoresCount() > 0) {
      hash = (37 * hash) + SCORES_FIELD_NUMBER;
      hash = (53 * hash) + getScoresList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.imooc.netty.mahjong.common.proto.SettlementNotification parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.imooc.netty.mahjong.common.proto.SettlementNotification parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.imooc.netty.mahjong.common.proto.SettlementNotification parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.imooc.netty.mahjong.common.proto.SettlementNotification parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.imooc.netty.mahjong.common.proto.SettlementNotification parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.imooc.netty.mahjong.common.proto.SettlementNotification parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.imooc.netty.mahjong.common.proto.SettlementNotification parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.imooc.netty.mahjong.common.proto.SettlementNotification parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.imooc.netty.mahjong.common.proto.SettlementNotification parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.imooc.netty.mahjong.common.proto.SettlementNotification parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.imooc.netty.mahjong.common.proto.SettlementNotification prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SettlementNotification}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SettlementNotification)
      com.imooc.netty.mahjong.common.proto.SettlementNotificationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.imooc.netty.mahjong.common.proto.Mahjong.internal_static_SettlementNotification_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.imooc.netty.mahjong.common.proto.Mahjong.internal_static_SettlementNotification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.imooc.netty.mahjong.common.proto.SettlementNotification.class, com.imooc.netty.mahjong.common.proto.SettlementNotification.Builder.class);
    }

    // Construct using com.imooc.netty.mahjong.common.proto.SettlementNotification.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      scores_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.imooc.netty.mahjong.common.proto.Mahjong.internal_static_SettlementNotification_descriptor;
    }

    public com.imooc.netty.mahjong.common.proto.SettlementNotification getDefaultInstanceForType() {
      return com.imooc.netty.mahjong.common.proto.SettlementNotification.getDefaultInstance();
    }

    public com.imooc.netty.mahjong.common.proto.SettlementNotification build() {
      com.imooc.netty.mahjong.common.proto.SettlementNotification result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.imooc.netty.mahjong.common.proto.SettlementNotification buildPartial() {
      com.imooc.netty.mahjong.common.proto.SettlementNotification result = new com.imooc.netty.mahjong.common.proto.SettlementNotification(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        scores_ = java.util.Collections.unmodifiableList(scores_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.scores_ = scores_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.imooc.netty.mahjong.common.proto.SettlementNotification) {
        return mergeFrom((com.imooc.netty.mahjong.common.proto.SettlementNotification)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.imooc.netty.mahjong.common.proto.SettlementNotification other) {
      if (other == com.imooc.netty.mahjong.common.proto.SettlementNotification.getDefaultInstance()) return this;
      if (!other.scores_.isEmpty()) {
        if (scores_.isEmpty()) {
          scores_ = other.scores_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureScoresIsMutable();
          scores_.addAll(other.scores_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.imooc.netty.mahjong.common.proto.SettlementNotification parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.imooc.netty.mahjong.common.proto.SettlementNotification) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<java.lang.Integer> scores_ = java.util.Collections.emptyList();
    private void ensureScoresIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        scores_ = new java.util.ArrayList<java.lang.Integer>(scores_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int32 scores = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getScoresList() {
      return java.util.Collections.unmodifiableList(scores_);
    }
    /**
     * <code>repeated int32 scores = 1;</code>
     */
    public int getScoresCount() {
      return scores_.size();
    }
    /**
     * <code>repeated int32 scores = 1;</code>
     */
    public int getScores(int index) {
      return scores_.get(index);
    }
    /**
     * <code>repeated int32 scores = 1;</code>
     */
    public Builder setScores(
        int index, int value) {
      ensureScoresIsMutable();
      scores_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 scores = 1;</code>
     */
    public Builder addScores(int value) {
      ensureScoresIsMutable();
      scores_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 scores = 1;</code>
     */
    public Builder addAllScores(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureScoresIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, scores_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 scores = 1;</code>
     */
    public Builder clearScores() {
      scores_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:SettlementNotification)
  }

  // @@protoc_insertion_point(class_scope:SettlementNotification)
  private static final com.imooc.netty.mahjong.common.proto.SettlementNotification DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.imooc.netty.mahjong.common.proto.SettlementNotification();
  }

  public static com.imooc.netty.mahjong.common.proto.SettlementNotification getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SettlementNotification>
      PARSER = new com.google.protobuf.AbstractParser<SettlementNotification>() {
    public SettlementNotification parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SettlementNotification(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SettlementNotification> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SettlementNotification> getParserForType() {
    return PARSER;
  }

  public com.imooc.netty.mahjong.common.proto.SettlementNotification getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

