// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package com.imooc.netty.samples.$34.proto;

public interface PlayerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Player)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
